version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - pip install pytest==3.6.3
      - pip install pyflakes==2.0.0
  build:
    commands:
      - pip install -r custom_chainer/requirements.txt
      - pip install -r custom_chainer/requirements_test_only.txt

      - pyflakes custom_chainer/**/*.py
      - pytest

  post_build:
    commands:
      - echo creating package
      - mkdir buildoutput
      - pip install -r custom_chainer/requirements.txt  -t custom_chainer
      - cd custom_chainer && zip -r ../buildoutput/sentimentanalysis_chainer.zip . && cd ..


artifacts:
  files:
    - '**/*'
  base-directory: buildoutput
