version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - pip install pytest -t custom_chainer
  build:
    commands:
      - pip install -r custom_chainer/requirements.txt -t custom_chainer
      - cd custom_chainer && pytest && cd ..
  post_build:
    commands:
      - echo creating package
      - mkdir buildoutput
      - cd custom_chainer && zip -r ../buildoutput/sentimentanalysis_chainer.zip . && cd ..


artifacts:
  files:
    - '**/*'
  base-directory: buildoutput
