version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - pip install pytest
  build:
    commands:
      - pip install -r custom_chainer/requirements.txt
      - pip install -r custom_chainer/requirements_test_only.txt
      - pytest
      - pip install -r custom_chainer/requirements.txt  -t custom_chainer
  post_build:
    commands:
      - echo creating package
      - mkdir buildoutput
      - cd custom_chainer && zip -r ../buildoutput/sentimentanalysis_chainer.zip . && cd ..


artifacts:
  files:
    - '**/*'
  base-directory: buildoutput
